service: mongodb-project
frameworkVersion: "3"

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-apigw-binary

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 1024
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

functions:
  # createProduct:
  #   handler: src/functions/create-product/handler.main
  #   timeout: 10
  #   events:
  #     - http:
  #         method: post
  #         path: create-product
  #         cors:
  #           origin: "*"
  #           headers:
  #             - Content-Type
  #             - Accept
  #             - X-Amz-Date
  getProduct:
    handler: src/functions/get-product/handler.main
    timeout: 10
    events:
      - http:
          method: get
          path: get-product/{id}
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Accept
              - X-Amz-Date

  getProducts:
    handler: src/functions/get-products/handler.main
    timeout: 10
    events:
      - http:
          method: get
          path: getProducts
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Accept
              - X-Amz-Date

  # deleteProduct:
  #   handler: src/functions/delete-product/handler.main
  #   timeout: 10
  #   events:
  #     - http:
  #         method: post
  #         path: delete-product/{id}
  #         cors:
  #           origin: "*"
  #           headers:
  #             - Content-Type
  #             - Accept
  #             - X-Amz-Date

package:
  individually: true
  excludeDevDependencies: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ["aws-sdk"]
    target: node18
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10

  serverless-offline:
    lambdaPort: 4000
    httpPort: 4001

  apigwBinary:
    types:
      - multipart/form-data
